import type {
  District,
  EnergyDataPoint,
  ARIALogEntry,
  EmergencyAsset,
  Incident,
  CitizenFeedReport,
  Issue,
  FairnessEntry,
  AccountabilityEntry,
} from "./types";

// ─── Districts ────────────────────────────────────────────────────────────────

export const DISTRICTS: District[] = [
  {
    id: "d1",
    name: "Central Hub",
    load: 78,
    status: "warning",
    trustIndex: 74,
    trafficLoad: 82,
    population: 124000,
    ariaAction: "Redistribute 12% load to District 3 buffer grid",
    coordinates: { x: 310, y: 200 },
  },
  {
    id: "d2",
    name: "Northgate",
    load: 45,
    status: "stable",
    trustIndex: 88,
    trafficLoad: 41,
    population: 89000,
    ariaAction: "Maintain current state — monitor solar input",
    coordinates: { x: 220, y: 100 },
  },
  {
    id: "d3",
    name: "Eastport",
    load: 91,
    status: "critical",
    trustIndex: 52,
    trafficLoad: 88,
    population: 156000,
    ariaAction: "Activate backup grid B-7, defer non-critical loads",
    coordinates: { x: 440, y: 190 },
  },
  {
    id: "d4",
    name: "Southvale",
    load: 63,
    status: "stable",
    trustIndex: 81,
    trafficLoad: 55,
    population: 102000,
    ariaAction: "No action required — operating within parameters",
    coordinates: { x: 320, y: 330 },
  },
  {
    id: "d5",
    name: "Westbridge",
    load: 97,
    status: "critical",
    trustIndex: 41,
    trafficLoad: 94,
    population: 178000,
    ariaAction: "Emergency reroute via District 2 — hospital priority lock",
    coordinates: { x: 160, y: 255 },
  },
  {
    id: "d6",
    name: "Midtown",
    load: 55,
    status: "stable",
    trustIndex: 79,
    trafficLoad: 67,
    population: 93000,
    ariaAction: "Charge buffer cells during off-peak window",
    coordinates: { x: 290, y: 270 },
  },
  {
    id: "d7",
    name: "Harbor Zone",
    load: 33,
    status: "stable",
    trustIndex: 92,
    trafficLoad: 28,
    population: 47000,
    ariaAction: "Sell 15% surplus to District 5 via smart grid",
    coordinates: { x: 420, y: 320 },
  },
  {
    id: "d8",
    name: "Industrial Fringe",
    load: 100,
    status: "blackout",
    trustIndex: 29,
    trafficLoad: 70,
    population: 31000,
    ariaAction: "Blackout Protocol: non-essential shutdown, alert crews",
    coordinates: { x: 130, y: 160 },
  },
];

// ─── Energy Time-Series ───────────────────────────────────────────────────────

function generateEnergyData(baseLoad: number): EnergyDataPoint[] {
  const points: EnergyDataPoint[] = [];
  for (let i = 23; i >= 0; i--) {
    const hour = new Date();
    hour.setHours(hour.getHours() - i);
    const variance = Math.sin(i * 0.4) * 12 + (Math.random() - 0.5) * 8;
    points.push({
      time: hour.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", hour12: false }),
      load: Math.min(100, Math.max(10, Math.round(baseLoad + variance))),
      capacity: 100,
    });
  }
  return points;
}

export const ENERGY_DATA: Record<string, EnergyDataPoint[]> = {
  d1: generateEnergyData(78),
  d2: generateEnergyData(45),
  d3: generateEnergyData(91),
  d4: generateEnergyData(63),
  d5: generateEnergyData(97),
  d6: generateEnergyData(55),
  d7: generateEnergyData(33),
  d8: generateEnergyData(100),
};

// ─── ARIA Reasoning Log ───────────────────────────────────────────────────────

export const ARIA_LOG_ENTRIES: ARIALogEntry[] = [
  {
    id: "log-001",
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    action: "Emergency reroute activated — District 5 to District 2 grid",
    reasoning:
      "Grid load at 97% in Westbridge. Hospital priority lock engaged. District 2 operating at 45% — 38% headroom available. Rerouting 20% residential load preserves critical infrastructure.",
    confidence: 94,
    confidenceLevel: "high",
    alternativeConsidered: "Brownout 8% non-essential commercial — rejected (trust index impact)",
    category: "energy",
    overridden: false,
  },
  {
    id: "log-002",
    timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    action: "District 8 Blackout Protocol initiated",
    reasoning:
      "Load sustained at 100% for 47 minutes. Thermal threshold exceeded. Industrial Fringe has lowest population density. ARIA initiated controlled shutdown to prevent cascade failure.",
    confidence: 88,
    confidenceLevel: "high",
    alternativeConsidered: "Rolling brownouts across 3 districts — rejected (complexity risk)",
    category: "energy",
    overridden: false,
  },
  {
    id: "log-003",
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    action: "Issue #ISS-014 scored High Priority (87% confidence)",
    reasoning:
      "Citizen report: transformer sparking in Westbridge. Cross-referenced with current 97% grid load. Combined risk score: 91/100. Escalated immediately.",
    confidence: 87,
    confidenceLevel: "high",
    alternativeConsidered: "Score as Medium — rejected due to grid load context",
    category: "issue",
    issueid: "ISS-014",
    overridden: false,
  },
  {
    id: "log-004",
    timestamp: new Date(Date.now() - 52 * 60000).toISOString(),
    action: "Drone DRN-04 dispatched to Eastport transformer fire",
    reasoning:
      "Incident severity: critical. Nearest available drone at 2.3km. Estimated arrival 4 minutes. Backup vehicle VEH-02 queued as secondary response.",
    confidence: 91,
    confidenceLevel: "high",
    alternativeConsidered: "Ground crew only — rejected (ETA 14min, unacceptable for critical)",
    category: "emergency",
    overridden: false,
  },
  {
    id: "log-005",
    timestamp: new Date(Date.now() - 1.2 * 3600000).toISOString(),
    action: "Issue #ISS-007 routed to Energy Management department",
    reasoning:
      "Category: energy. District: Eastport (critical status). Admin approved routing. Recommended resource: Repair crew + drone survey.",
    confidence: 82,
    confidenceLevel: "high",
    alternativeConsidered: "Route to General Services — rejected (specialization mismatch)",
    category: "issue",
    issueid: "ISS-007",
    overridden: false,
  },
  {
    id: "log-006",
    timestamp: new Date(Date.now() - 1.8 * 3600000).toISOString(),
    action: "Traffic rerouting recommended — Central Hub congestion",
    reasoning:
      "Traffic load at 82% in Central Hub. Secondary routes via Midtown operating at 67%. Projected 23% congestion reduction with smart signal adjustment.",
    confidence: 76,
    confidenceLevel: "medium",
    alternativeConsidered: "Close arterial road — rejected (emergency vehicle access requirement)",
    category: "energy",
    overridden: false,
  },
  {
    id: "log-007",
    timestamp: new Date(Date.now() - 2.4 * 3600000).toISOString(),
    action: "Harbor Zone surplus sold to Westbridge — 15% transfer",
    reasoning:
      "District 7 at 33% load with 15% surplus. District 5 at 97%. Smart grid transfer reduces cascade risk by 31%. Revenue offset to District 7 citizens.",
    confidence: 95,
    confidenceLevel: "high",
    alternativeConsidered: "Store in battery buffer — rejected (buffer already at 89%)",
    category: "energy",
    overridden: false,
  },
  {
    id: "log-008",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    action: "OVERRIDE: Admin rejected ARIA routing for Issue #ISS-003",
    reasoning:
      "ARIA recommended Emergency Response. Admin overrode to Traffic Control. Justification: 'Road marking issue, not emergency severity.'",
    confidence: 64,
    confidenceLevel: "medium",
    alternativeConsidered: "N/A — human override applied",
    category: "override",
    issueid: "ISS-003",
    overridden: true,
  },
  {
    id: "log-009",
    timestamp: new Date(Date.now() - 4.2 * 3600000).toISOString(),
    action: "Issue #ISS-011 scored Medium Priority (71% confidence)",
    reasoning:
      "Citizen report: Flickering streetlights in Southvale. No grid anomaly detected. Likely maintenance issue. Scheduled for routine inspection queue.",
    confidence: 71,
    confidenceLevel: "medium",
    alternativeConsidered: "Score as Low — rejected (multiple reports from same area)",
    category: "issue",
    issueid: "ISS-011",
    overridden: false,
  },
  {
    id: "log-010",
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    action: "Predictive Risk Radar: 68% cascade risk — District 4 in 3hr",
    reasoning:
      "Thermal model predicts load spike based on weather forecast (+8°C) and event schedule (stadium capacity). Preventive measures recommended.",
    confidence: 68,
    confidenceLevel: "medium",
    alternativeConsidered: "Alert only — rejected (historical cascade pattern match)",
    category: "energy",
    overridden: false,
  },
  {
    id: "log-011",
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    action: "Issue #ISS-019 scored Low Priority (55% confidence)",
    reasoning:
      "Citizen feedback: Noise complaint near Industrial Fringe. Outside ARIA energy/safety domain. Low urgency. Routed to General Services.",
    confidence: 55,
    confidenceLevel: "low",
    alternativeConsidered: "Ignore — rejected (citizen trust index consideration)",
    category: "issue",
    issueid: "ISS-019",
    overridden: false,
  },
  {
    id: "log-012",
    timestamp: new Date(Date.now() - 7.5 * 3600000).toISOString(),
    action: "Resource allocation: DRN-02 reassigned to Harbor Zone patrol",
    reasoning:
      "Incident in Harbor Zone downgraded from critical to medium. DRN-02 en route redirected. VEH-01 sufficient for remaining response.",
    confidence: 83,
    confidenceLevel: "high",
    alternativeConsidered: "Maintain DRN-02 course — rejected (resource efficiency)",
    category: "emergency",
    overridden: false,
  },
  {
    id: "log-013",
    timestamp: new Date(Date.now() - 9 * 3600000).toISOString(),
    action: "Issue #ISS-002 resource recommendation: Repair Crew + Drone",
    reasoning:
      "Power outage in Eastport residential block. Crew needed for physical repair. Drone for aerial survey of affected area extent.",
    confidence: 89,
    confidenceLevel: "high",
    alternativeConsidered: "Drone only — rejected (physical intervention required)",
    category: "issue",
    issueid: "ISS-002",
    overridden: false,
  },
  {
    id: "log-014",
    timestamp: new Date(Date.now() - 11 * 3600000).toISOString(),
    action: "OVERRIDE: ARIA brownout rejected by Admin — District 3",
    reasoning:
      "ARIA recommended 10% brownout for Eastport to prevent critical failure. Human operator overrode — preferred demand response appeal to residents.",
    confidence: 79,
    confidenceLevel: "medium",
    alternativeConsidered: "N/A — human override applied",
    category: "override",
    overridden: true,
  },
  {
    id: "log-015",
    timestamp: new Date(Date.now() - 14 * 3600000).toISOString(),
    action: "Fairness flag raised: District 8 disproportionate impact",
    reasoning:
      "Industrial Fringe has experienced 3 blackouts in 7 days vs city avg 0.4. Trust index dropped from 61 to 29. Equity review recommended.",
    confidence: 97,
    confidenceLevel: "high",
    alternativeConsidered: "No action — rejected (ethical mandate)",
    category: "energy",
    overridden: false,
  },
];

// ─── Emergency Assets ─────────────────────────────────────────────────────────

export const EMERGENCY_ASSETS: EmergencyAsset[] = [
  { id: "drn-01", type: "drone", name: "DRN-01 Falcon", status: "On Site", district: "Eastport", coordinates: { x: 440, y: 190 }, assignedIncident: "inc-001" },
  { id: "drn-02", type: "drone", name: "DRN-02 Hawk", status: "Returning", district: "Harbor Zone", coordinates: { x: 420, y: 320 } },
  { id: "drn-03", type: "drone", name: "DRN-03 Eagle", status: "Standby", district: "Northgate", coordinates: { x: 220, y: 100 } },
  { id: "drn-04", type: "drone", name: "DRN-04 Osprey", status: "En Route", district: "Westbridge", coordinates: { x: 160, y: 255 }, assignedIncident: "inc-002" },
  { id: "veh-01", type: "vehicle", name: "VEH-01 Rapid Response", status: "On Site", district: "Industrial Fringe", coordinates: { x: 130, y: 160 }, assignedIncident: "inc-003" },
  { id: "veh-02", type: "vehicle", name: "VEH-02 Repair Unit", status: "En Route", district: "Eastport", coordinates: { x: 400, y: 200 }, assignedIncident: "inc-001" },
  { id: "veh-03", type: "vehicle", name: "VEH-03 Crew Alpha", status: "Standby", district: "Central Hub", coordinates: { x: 310, y: 200 } },
  { id: "sns-01", type: "sensor", name: "SNS-01 Grid Monitor", status: "On Site", district: "Westbridge", coordinates: { x: 175, y: 240 } },
  { id: "sns-02", type: "sensor", name: "SNS-02 Traffic Cam", status: "On Site", district: "Central Hub", coordinates: { x: 325, y: 215 } },
  { id: "sns-03", type: "sensor", name: "SNS-03 Air Quality", status: "On Site", district: "Industrial Fringe", coordinates: { x: 145, y: 175 } },
  { id: "sns-04", type: "sensor", name: "SNS-04 Flood Sensor", status: "On Site", district: "Harbor Zone", coordinates: { x: 435, y: 310 } },
  { id: "veh-04", type: "vehicle", name: "VEH-04 Hazmat Unit", status: "Standby", district: "Southvale", coordinates: { x: 320, y: 330 } },
];

export const INCIDENTS: Incident[] = [
  {
    id: "inc-001",
    title: "Transformer Fire — Eastport Substation",
    severity: "critical",
    district: "Eastport",
    description: "Primary transformer at substation E-7 caught fire following sustained overload. Fire suppression active. Power interrupted to ~8,000 residents.",
    reportedAt: new Date(Date.now() - 28 * 60000).toISOString(),
    assignedAssets: ["drn-01", "veh-02"],
    issueId: "ISS-007",
  },
  {
    id: "inc-002",
    title: "Grid Cascade Risk — Westbridge Residential",
    severity: "critical",
    district: "Westbridge",
    description: "Load at 97%. Cascade failure probability rising. Drone dispatched for aerial assessment and sensor deployment.",
    reportedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    assignedAssets: ["drn-04"],
    issueId: "ISS-014",
  },
  {
    id: "inc-003",
    title: "Industrial Blackout Response",
    severity: "high",
    district: "Industrial Fringe",
    description: "Full blackout active. Rapid response vehicle securing perimeter. Non-essential personnel evacuation in progress.",
    reportedAt: new Date(Date.now() - 52 * 60000).toISOString(),
    assignedAssets: ["veh-01"],
  },
  {
    id: "inc-004",
    title: "Traffic Signal Failure — Central Hub",
    severity: "medium",
    district: "Central Hub",
    description: "Multiple intersections with signal failure causing gridlock on main arterials. Traffic sensor deployed.",
    reportedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    assignedAssets: ["sns-02"],
  },
  {
    id: "inc-005",
    title: "Flooding Alert — Harbor Zone Dock 3",
    severity: "medium",
    district: "Harbor Zone",
    description: "Abnormal tidal surge detected. Flood sensor monitoring water levels. Preventive barriers deployed.",
    reportedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    assignedAssets: ["sns-04"],
  },
];

// ─── Citizen Feed Reports ─────────────────────────────────────────────────────

export const CITIZEN_FEED: CitizenFeedReport[] = [
  { id: "cf-001", citizen: "Maya Chen", district: "Eastport", message: "Power has been out for 3 hours in block 7E. My elderly neighbor is on oxygen equipment. This is urgent!", sentiment: "negative", timestamp: new Date(Date.now() - 25 * 60000).toISOString(), category: "energy" },
  { id: "cf-002", citizen: "James Okafor", district: "Westbridge", message: "ARIA's rerouting notice came to my app. Good communication, but concerned about how long this will last.", sentiment: "neutral", timestamp: new Date(Date.now() - 40 * 60000).toISOString(), category: "energy" },
  { id: "cf-003", citizen: "Priya Nair", district: "Northgate", message: "Love the new smart grid updates! Solar panels sharing power with neighbors is brilliant.", sentiment: "positive", timestamp: new Date(Date.now() - 1.1 * 3600000).toISOString(), category: "energy" },
  { id: "cf-004", citizen: "Aleksei Petrov", district: "Industrial Fringe", message: "Third blackout this week. We need answers from the city. Our business lost critical data again.", sentiment: "negative", timestamp: new Date(Date.now() - 1.5 * 3600000).toISOString(), category: "energy" },
  { id: "cf-005", citizen: "Sofia Martinez", district: "Central Hub", message: "Traffic signals on Main & 5th have been broken for 2 days. Almost caused an accident this morning.", sentiment: "negative", timestamp: new Date(Date.now() - 2 * 3600000).toISOString(), category: "traffic" },
  { id: "cf-006", citizen: "Liam O'Brien", district: "Southvale", message: "City's new emergency response drones are impressive. Saw one respond to the Eastport situation within minutes.", sentiment: "positive", timestamp: new Date(Date.now() - 2.5 * 3600000).toISOString(), category: "other" },
  { id: "cf-007", citizen: "Amara Diallo", district: "Midtown", message: "ARIA's AI explanations on the citizen portal are actually helpful. I understand why my area was prioritized.", sentiment: "positive", timestamp: new Date(Date.now() - 3 * 3600000).toISOString(), category: "other" },
  { id: "cf-008", citizen: "Chen Wei", district: "Harbor Zone", message: "Flood sensor alerts were super timely. We moved our gear before the surge hit. Great system!", sentiment: "positive", timestamp: new Date(Date.now() - 3.5 * 3600000).toISOString(), category: "safety" },
  { id: "cf-009", citizen: "Fatima Al-Hassan", district: "Eastport", message: "Why is our district always the one with critical status? Feels like Eastport is always deprioritized.", sentiment: "negative", timestamp: new Date(Date.now() - 4 * 3600000).toISOString(), category: "energy" },
  { id: "cf-010", citizen: "Diego Ruiz", district: "Westbridge", message: "Received brownout notification 10 minutes before it happened. Appreciate the heads up but cuts are getting frequent.", sentiment: "neutral", timestamp: new Date(Date.now() - 4.5 * 3600000).toISOString(), category: "energy" },
  { id: "cf-011", citizen: "Hannah Kim", district: "Northgate", message: "Energy bill dropped 18% since the smart grid launched. Very happy with the changes here.", sentiment: "positive", timestamp: new Date(Date.now() - 5 * 3600000).toISOString(), category: "energy" },
  { id: "cf-012", citizen: "Oumar Cissé", district: "Industrial Fringe", message: "This is the third time Industrial Fringe is cut off while other districts run at full power. Discrimination?", sentiment: "negative", timestamp: new Date(Date.now() - 5.5 * 3600000).toISOString(), category: "energy" },
  { id: "cf-013", citizen: "Elena Volkov", district: "Midtown", message: "The ARIA confidence scores on the city dashboard are confusing for regular citizens. Could use simpler language.", sentiment: "neutral", timestamp: new Date(Date.now() - 6 * 3600000).toISOString(), category: "other" },
  { id: "cf-014", citizen: "Marcus Thompson", district: "Southvale", message: "Street lights on Grove Ave have been flickering for a week. Already reported twice with no response.", sentiment: "negative", timestamp: new Date(Date.now() - 7 * 3600000).toISOString(), category: "safety" },
  { id: "cf-015", citizen: "Yuki Tanaka", district: "Harbor Zone", message: "Appreciate the transparent AI decision logs. Nice to know why load was shifted away from our area today.", sentiment: "positive", timestamp: new Date(Date.now() - 8 * 3600000).toISOString(), category: "energy" },
  { id: "cf-016", citizen: "Rosa Delgado", district: "Central Hub", message: "Bus schedules are completely off due to traffic chaos. Signal failures are cascading into transport problems.", sentiment: "negative", timestamp: new Date(Date.now() - 9 * 3600000).toISOString(), category: "traffic" },
  { id: "cf-017", citizen: "Ahmed Khalid", district: "Westbridge", message: "ARIA prioritized hospital power correctly. Even though my area had cuts, I understand and support the decision.", sentiment: "positive", timestamp: new Date(Date.now() - 10 * 3600000).toISOString(), category: "energy" },
  { id: "cf-018", citizen: "Nadia Patel", district: "Eastport", message: "Repair crew arrived within an hour of the fire report. Efficient response. Power restored to half the block.", sentiment: "positive", timestamp: new Date(Date.now() - 11 * 3600000).toISOString(), category: "energy" },
  { id: "cf-019", citizen: "Robert James", district: "Industrial Fringe", message: "Hazmat concern near Sector 4. Smelled something chemical after the blackout. Anyone investigating?", sentiment: "negative", timestamp: new Date(Date.now() - 12 * 3600000).toISOString(), category: "safety" },
  { id: "cf-020", citizen: "Isabella Costa", district: "Southvale", message: "Really smooth experience with the app. Reported an issue and got a status update within the hour. 10/10.", sentiment: "positive", timestamp: new Date(Date.now() - 13 * 3600000).toISOString(), category: "other" },
  { id: "cf-021", citizen: "Patrick Chen", district: "Northgate", message: "Solar energy sharing program is exactly what the community needed. Northgate feels like a pilot for the future.", sentiment: "positive", timestamp: new Date(Date.now() - 14 * 3600000).toISOString(), category: "energy" },
  { id: "cf-022", citizen: "Layla Hassan", district: "Midtown", message: "Midtown has had no major incidents in a week. Stable grid is a relief after months of disruptions.", sentiment: "positive", timestamp: new Date(Date.now() - 15 * 3600000).toISOString(), category: "energy" },
  { id: "cf-023", citizen: "Victor Petrov", district: "Industrial Fringe", message: "Workers are standing outside in the heat with no power. This is a health hazard, not just inconvenience.", sentiment: "negative", timestamp: new Date(Date.now() - 16 * 3600000).toISOString(), category: "safety" },
  { id: "cf-024", citizen: "Mele Tupou", district: "Harbor Zone", message: "The flood sensors gave us a 30-min warning. Dock 3 crew secured everything. Excellent technology!", sentiment: "positive", timestamp: new Date(Date.now() - 17 * 3600000).toISOString(), category: "safety" },
  { id: "cf-025", citizen: "Francine Dubois", district: "Central Hub", message: "The traffic AI rerouting suggestion on the app helped me avoid the gridlock today. Very useful feature.", sentiment: "positive", timestamp: new Date(Date.now() - 18 * 3600000).toISOString(), category: "traffic" },
  { id: "cf-026", citizen: "Kai Müller", district: "Westbridge", message: "Power keeps cutting out for 10-15min intervals. Appliances are getting damaged. Need compensation process.", sentiment: "negative", timestamp: new Date(Date.now() - 19 * 3600000).toISOString(), category: "energy" },
  { id: "cf-027", citizen: "Sana Iqbal", district: "Southvale", message: "ARIA scheduled maintenance perfectly — notified a day ahead and power was only out 40 mins. Painless!", sentiment: "positive", timestamp: new Date(Date.now() - 20 * 3600000).toISOString(), category: "energy" },
  { id: "cf-028", citizen: "Benjamin Osei", district: "Eastport", message: "Three separate crews came to fix same problem. Coordination seems broken on the ground despite good AI planning.", sentiment: "neutral", timestamp: new Date(Date.now() - 21 * 3600000).toISOString(), category: "other" },
  { id: "cf-029", citizen: "Zara Williams", district: "Industrial Fringe", message: "City officials need to visit Industrial Fringe in person. The data doesn't capture how bad it is on the ground.", sentiment: "negative", timestamp: new Date(Date.now() - 22 * 3600000).toISOString(), category: "other" },
  { id: "cf-030", citizen: "Tomas Kowalski", district: "Harbor Zone", message: "Completely happy with city services in Harbor Zone. Best-managed district in Aegis City, IMO.", sentiment: "positive", timestamp: new Date(Date.now() - 24 * 3600000).toISOString(), category: "other" },
];

// ─── Seeded Issues (3-Role Pipeline) ─────────────────────────────────────────

export const SEED_ISSUES: Issue[] = [
  {
    id: "ISS-001",
    citizenId: "cit-001",
    citizenName: "Maya Chen",
    category: "energy",
    district: "Eastport",
    description: "Power out for 3+ hours in block 7E. Elderly neighbor on oxygen equipment needs urgent power restoration.",
    urgency: 5,
    status: "In Progress",
    submittedAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 93,
    ariaRecommendedResource: "Repair Crew + Drone Survey",
    routedTo: "Energy Management",
    assignedResource: "VEH-02 Repair Unit + DRN-01",
  },
  {
    id: "ISS-002",
    citizenId: "cit-004",
    citizenName: "Aleksei Petrov",
    category: "energy",
    district: "Industrial Fringe",
    description: "Third blackout this week. Lost critical business data. Need urgent resolution and compensation process.",
    urgency: 5,
    status: "Approved & Routed",
    submittedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 89,
    ariaRecommendedResource: "Repair Crew + Grid Engineers",
    routedTo: "Energy Management",
  },
  {
    id: "ISS-003",
    citizenId: "cit-005",
    citizenName: "Sofia Martinez",
    category: "traffic",
    district: "Central Hub",
    description: "Traffic signals on Main & 5th broken for 2 days. Near accident this morning. Urgent safety risk.",
    urgency: 4,
    status: "In Progress",
    submittedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 74,
    ariaRecommendedResource: "Traffic Control Team",
    routedTo: "Traffic Control",
    adminNotes: "ARIA recommended Emergency Response but reclassified to Traffic Control.",
    assignedResource: "Traffic Signal Crew",
  },
  {
    id: "ISS-004",
    citizenId: "cit-014",
    citizenName: "Marcus Thompson",
    category: "safety",
    district: "Southvale",
    description: "Street lights on Grove Ave flickering for a week. Dark patches creating safety risk at night.",
    urgency: 3,
    status: "Under Admin Review",
    submittedAt: new Date(Date.now() - 7 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    ariaPriority: "Medium",
    ariaConfidence: 71,
    ariaRecommendedResource: "Electrical Maintenance Crew",
    routedTo: null,
  },
  {
    id: "ISS-005",
    citizenId: "cit-019",
    citizenName: "Robert James",
    category: "safety",
    district: "Industrial Fringe",
    description: "Chemical smell near Sector 4 after the blackout. Possible hazmat situation. Needs investigation.",
    urgency: 5,
    status: "In Progress",
    submittedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 91,
    ariaRecommendedResource: "Hazmat Unit + Environmental Sensor",
    routedTo: "Public Safety",
    assignedResource: "VEH-04 Hazmat + SNS-03",
  },
  {
    id: "ISS-006",
    citizenId: "cit-013",
    citizenName: "Elena Volkov",
    category: "other",
    district: "Midtown",
    description: "ARIA confidence scores on city dashboard are too technical. Citizens need simpler explanations.",
    urgency: 2,
    status: "Resolved",
    submittedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    ariaPriority: "Low",
    ariaConfidence: 55,
    ariaRecommendedResource: "UX/Communications Team",
    routedTo: "General Services",
    resolvedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "ISS-007",
    citizenId: "cit-009",
    citizenName: "Fatima Al-Hassan",
    category: "energy",
    district: "Eastport",
    description: "Eastport district is always in critical status. Requesting transparent explanation of prioritization algorithm.",
    urgency: 3,
    status: "Approved & Routed",
    submittedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    ariaPriority: "Medium",
    ariaConfidence: 82,
    ariaRecommendedResource: "Policy & Communications Team",
    routedTo: "Energy Management",
  },
  {
    id: "ISS-008",
    citizenId: "cit-026",
    citizenName: "Kai Müller",
    category: "energy",
    district: "Westbridge",
    description: "Power cuts every 10-15 minutes damaging appliances. Need immediate stabilization and compensation process.",
    urgency: 4,
    status: "Under Admin Review",
    submittedAt: new Date(Date.now() - 19 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 85,
    ariaRecommendedResource: "Grid Stabilization Team",
    routedTo: null,
  },
  {
    id: "ISS-009",
    citizenId: "cit-029",
    citizenName: "Zara Williams",
    category: "other",
    district: "Industrial Fringe",
    description: "Request for city officials to conduct in-person visit to Industrial Fringe. Data doesn't capture ground reality.",
    urgency: 3,
    status: "Rejected",
    submittedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2.5 * 86400000).toISOString(),
    ariaPriority: "Low",
    ariaConfidence: 48,
    ariaRecommendedResource: "General Services",
    routedTo: null,
    rejectionReason: "Administrative visit requests handled through formal council process. Redirected to council portal.",
  },
  {
    id: "ISS-010",
    citizenId: "cit-016",
    citizenName: "Rosa Delgado",
    category: "traffic",
    district: "Central Hub",
    description: "Bus schedules completely disrupted due to traffic signal failures. Cascading public transport issues.",
    urgency: 4,
    status: "Approved & Routed",
    submittedAt: new Date(Date.now() - 9 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 79,
    ariaRecommendedResource: "Traffic + Transit Teams",
    routedTo: "Traffic Control",
  },
  {
    id: "ISS-011",
    citizenId: "cit-002",
    citizenName: "James Okafor",
    category: "energy",
    district: "Westbridge",
    description: "ARIA rerouting causing unpredictable power availability. Need stable schedule of planned cuts if unavoidable.",
    urgency: 3,
    status: "Under Admin Review",
    submittedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    ariaPriority: "Medium",
    ariaConfidence: 71,
    ariaRecommendedResource: "Communications + Grid Team",
    routedTo: null,
  },
  {
    id: "ISS-012",
    citizenId: "cit-023",
    citizenName: "Victor Petrov",
    category: "safety",
    district: "Industrial Fringe",
    description: "Workers in heat with no power — health hazard. Urgent cooling and power restoration needed.",
    urgency: 5,
    status: "In Progress",
    submittedAt: new Date(Date.now() - 16 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 95,
    ariaRecommendedResource: "Emergency Medical + Power Crew",
    routedTo: "Emergency Response",
    assignedResource: "VEH-01 Rapid Response",
  },
  {
    id: "ISS-013",
    citizenId: "cit-028",
    citizenName: "Benjamin Osei",
    category: "other",
    district: "Eastport",
    description: "Multiple repair crews coming to same location creating confusion. Poor ground coordination despite good AI planning.",
    urgency: 2,
    status: "Resolved",
    submittedAt: new Date(Date.now() - 21 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 3600000).toISOString(),
    ariaPriority: "Low",
    ariaConfidence: 62,
    ariaRecommendedResource: "Operations Coordinator",
    routedTo: "General Services",
    resolvedAt: new Date(Date.now() - 15 * 3600000).toISOString(),
  },
  {
    id: "ISS-014",
    citizenId: "cit-010",
    citizenName: "Diego Ruiz",
    category: "energy",
    district: "Westbridge",
    description: "Saw sparks from transformer near Westbridge Residential Block C. Potential fire risk. Urgent inspection needed.",
    urgency: 5,
    status: "In Progress",
    submittedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 87,
    ariaRecommendedResource: "Fire Safety + Drone Survey",
    routedTo: "Emergency Response",
    assignedResource: "DRN-04 Osprey",
  },
  {
    id: "ISS-015",
    citizenId: "cit-020",
    citizenName: "Isabella Costa",
    category: "other",
    district: "Southvale",
    description: "Positive feedback: Issue response was quick and professional. Recommending public recognition for the team.",
    urgency: 1,
    status: "Resolved",
    submittedAt: new Date(Date.now() - 13 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    ariaPriority: "Low",
    ariaConfidence: 45,
    ariaRecommendedResource: "General Services",
    routedTo: "General Services",
    resolvedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: "ISS-016",
    citizenId: "cit-022",
    citizenName: "Layla Hassan",
    category: "energy",
    district: "Midtown",
    description: "Midtown has been stable for a week! Reporting to acknowledge the improvement in grid management.",
    urgency: 1,
    status: "Submitted",
    submittedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
    ariaPriority: "Low",
    ariaConfidence: 42,
    ariaRecommendedResource: "General Services",
    routedTo: null,
  },
  {
    id: "ISS-017",
    citizenId: "cit-024",
    citizenName: "Mele Tupou",
    category: "safety",
    district: "Harbor Zone",
    description: "Flood sensor gave excellent 30-min warning. But the alarm sound is too quiet for dock workers. Needs amplification.",
    urgency: 2,
    status: "Submitted",
    submittedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    ariaPriority: "Medium",
    ariaConfidence: 67,
    ariaRecommendedResource: "Infrastructure Maintenance",
    routedTo: null,
  },
  {
    id: "ISS-018",
    citizenId: "cit-012",
    citizenName: "Oumar Cissé",
    category: "energy",
    district: "Industrial Fringe",
    description: "Demanding equity audit. Industrial Fringe cut off while other districts run at full power. Systematic discrimination suspected.",
    urgency: 4,
    status: "Under Admin Review",
    submittedAt: new Date(Date.now() - 5.5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    ariaPriority: "High",
    ariaConfidence: 88,
    ariaRecommendedResource: "Equity Review Board",
    routedTo: null,
  },
  {
    id: "ISS-019",
    citizenId: "cit-011",
    citizenName: "Hannah Kim",
    category: "energy",
    district: "Northgate",
    description: "Energy bill dropped 18%! Would love to see this solar sharing program expanded across more districts.",
    urgency: 1,
    status: "Resolved",
    submittedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    ariaPriority: "Low",
    ariaConfidence: 55,
    ariaRecommendedResource: "General Services",
    routedTo: "General Services",
    resolvedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: "ISS-020",
    citizenId: "cit-008",
    citizenName: "Chen Wei",
    category: "safety",
    district: "Harbor Zone",
    description: "Flood barriers deployed but some sections near Dock 5 appear to have gaps. Needs physical inspection.",
    urgency: 3,
    status: "Approved & Routed",
    submittedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600000).toISOString(),
    ariaPriority: "Medium",
    ariaConfidence: 76,
    ariaRecommendedResource: "Infrastructure + Sensor Crew",
    routedTo: "Public Safety",
  },
];

// ─── Fairness Data ────────────────────────────────────────────────────────────

export const FAIRNESS_DATA: FairnessEntry[] = [
  { district: "Central Hub", energyImpact: 42, serviceLevel: 74, reportRejectionRate: 8, flagged: false },
  { district: "Northgate", energyImpact: 18, serviceLevel: 92, reportRejectionRate: 4, flagged: false },
  { district: "Eastport", energyImpact: 74, serviceLevel: 53, reportRejectionRate: 12, flagged: false },
  { district: "Southvale", energyImpact: 31, serviceLevel: 80, reportRejectionRate: 5, flagged: false },
  { district: "Westbridge", energyImpact: 81, serviceLevel: 44, reportRejectionRate: 9, flagged: false },
  { district: "Midtown", energyImpact: 27, serviceLevel: 78, reportRejectionRate: 6, flagged: false },
  { district: "Harbor Zone", energyImpact: 12, serviceLevel: 94, reportRejectionRate: 3, flagged: false },
  { district: "Industrial Fringe", energyImpact: 97, serviceLevel: 28, reportRejectionRate: 28, flagged: true },
];

export const TRUST_HISTORY = [
  { day: "Mon", trust: 61 },
  { day: "Tue", trust: 58 },
  { day: "Wed", trust: 55 },
  { day: "Thu", trust: 53 },
  { day: "Fri", trust: 57 },
  { day: "Sat", trust: 61 },
  { day: "Sun", trust: 63 },
];

export const ACCOUNTABILITY_LOG: AccountabilityEntry[] = [
  { id: "acl-001", action: "Override: ARIA brownout rejected", actor: "Admin Okonkwo", timestamp: new Date(Date.now() - 11 * 3600000).toISOString(), justification: "Preferred demand-response appeal over forced brownout.", district: "Eastport" },
  { id: "acl-002", action: "Override: Issue routing changed to Traffic Control", actor: "Admin Okonkwo", timestamp: new Date(Date.now() - 3 * 3600000).toISOString(), justification: "Road marking issue — not emergency severity as ARIA flagged.", district: "Central Hub" },
  { id: "acl-003", action: "Issue ISS-009 rejected", actor: "Admin Reyes", timestamp: new Date(Date.now() - 2.5 * 86400000).toISOString(), justification: "In-person visit requests handled via formal council process.", district: "Industrial Fringe" },
  { id: "acl-004", action: "Manual grid reroute approved", actor: "Admin Patel", timestamp: new Date(Date.now() - 6 * 3600000).toISOString(), justification: "ARIA recommendation confirmed and expedited for hospital priority.", district: "Westbridge" },
  { id: "acl-005", action: "Issue ISS-018 held for equity review", actor: "Admin Okonkwo", timestamp: new Date(Date.now() - 2 * 3600000).toISOString(), justification: "Equity audit requested — escalating to fairness board before routing.", district: "Industrial Fringe" },
];
